### ISSUE TITLE
Include a LICENSE file into the package

### ISSUE THREAD

**Issue by nicoddemus** [jeffkaufman/icdiff#137]
Hi,

I'm about to build a `conda` package for this module (and `pytest-icdiff`), but I notice that there's no LICENSE file in the PyPI package, which conda-forge recommends all packages to have.

Any chance you could include a LICENSE file into your PyPI package?

**Comment by jeffkaufman** [comment]
added, and released 1.9.3

@vnitinv would you be able to update PiPy?

**Comment by nicoddemus** [comment]
Thanks @jeffkaufman.

I noticed you include the `LICENSE` file in the repository, but I think you also need to include it in the `MANIFEST.in` for it to be packaged into the `sdist`.

**Comment by jeffkaufman** [comment]
done: 2e2f00c

Do you also need a new release?

**Comment by nicoddemus** [comment]
Not need, as a workaround I've put the `LICENSE` file in the conda recipe manually: 

https://github.com/conda-forge/icdiff-feedstock/blob/25934c48457817ddc5803a5066fc9248c55592b3/recipe/meta.yaml#L37-L38

When the next release comes around I will just remove it and use the file from the package.

Thanks for the quick fix!

**Comment by nicoddemus** [comment]
Hi @jeffkaufman,

FWIW the `2.0.3` release still doesn't have a `LICENSE` file.

**Comment by jeffkaufman** [comment]
Sorry, forgot about this.  Released 2.0.4 which does
